language: node_js
node_js:
  - "lts/*"
install:
  - yarn install
services:
  - docker
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: yarn run test
    - name: "Submit test coverage"
      script: yarn run test:coverage
    - name: "Lint"
      script: yarn run lint:fix
    - stage: "Deploy"
      name: "Semantic Release"
      script:
        - docker build -t dicediscord/bot .
        - yarn run semantic-release
