language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
services:
  - docker
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: yarn run test
    - name: "Submit test coverage"
      script: yarn run test:coverage
    - name: "Lint"
      script: yarn run lint
    - stage: "Deploy"
      name: "Semantic Release"
      script:
        - docker build -t dicediscord/bot .
        - yarn run semantic-release
