language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: pnpm run test
    - name: "Submit test coverage"
      script: pnpm run test:coverage
    - name: "Lint"
      script: pnpm run lint:fix
    - stage: "Deploy"
      name: "Semantic Release"
      script:
        # Installs or loads Google Cloud CLI
        - if [ gcloud version || true -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        # Add gcloud to $PATH
        - source /home/travis/google-cloud-sdk/path.bash.inc
        # Generate revision ID for Stackdriver Debug
        - gcloud debug source gen-repo-info-file --output-directory=src
        - docker build -t dicediscord/bot .
        - pnpx semantic-release
