version: '3.7'
volumes:
  portainer_data:
services:
  bot:
    image: dicediscord/bot
    restart: always
    env_file: .env
    volumes:
      - ./googleCloudServiceAccount.json:/usr/src/dice/googleCloudServiceAccount.json:ro
    ports:
      - 5000:5000
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  dd-agent:
    image: datadog/agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent-conf.d:/conf.d:ro
    env_file: .env
  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
